### ISSUE TITLE
Has anyone already tried this repo and verify the results are good?

### ISSUE THREAD

**Issue by jwyang-google** [huggingface/bloom-jax-inference#7]
Hi, I am trying to find BLOOM model in JAX. Thanks for the great work.

Just want to first check if anyone has been running this JAX inference and compare results with PyTorch BLOOM model and verify the results are good?

Thanks

**Comment by Narsil** [comment]
We did at the time when this was developped.

You can never have 100% the same output on different hardware and different runtime engine, however the results were close enough.

Now lots of time has passed since and other things might have changes, the libraries we use, the config on the hub etc... So please do triple check before using.
